### ISSUE TITLE
help! pixel font totally borked

### ISSUE THREAD

**Issue by increpare** [increpare/terrylibtodo#56]
example five. not displaying pixel font :( i don't understand why, yet. (simple examples it still works for). it's using some other font instead :S

**Comment by increpare** [comment]
it works for the cursor coordinate display in that example still, though. I don't get it.

<img width="365" alt="screen shot 2015-08-28 at 17 12 21" src="https://cloud.githubusercontent.com/assets/465632/9551289/1623955e-4da8-11e5-937f-548136e1a020.png">

**Comment by increpare** [comment]
the pixel font appears correctly on the cursor not when it's initially loaded and compiled (the other horrible font appears the first time), but only when you hit run a second time.

**Comment by TerryCavanagh** [comment]
This is because of https://github.com/increpare/terrylibtodo/issues/39, which I'm still trying to figure out :( Added a new preloader class this morning, but it didn't help...

**Comment by increpare** [comment]
Ok. I guess I can still do a bit of on the music proj, it just looks crazy gross.   Thanks for letting me know :)

**Comment by TerryCavanagh** [comment]
Ok, I think I've fixed it! Feel free to reopen this if I'm wrong :D

**Comment by increpare** [comment]
yay. thanks so much! :)
